---
title: "R Notebook"
output:
  html_document:
    df_print: paged


```{r}
ruta_mac <- ''
ruta_win <- 'D:\\Datasets\\defunciones_deis_abierto\\'
print('Ingresar el sistema operativo (win o mac)')
so = readline(); 

if (so == 'win'){
nombre_archivo <- paste(ruta_win,'DEF_1990_2018.csv', sep="")
bd = read.csv2(nombre_archivo)
} else {
  print('Agregar ruta del mac')
}
```


```{r}
attach(bd)
```


```{r}
library(nortest)
edad = bd$EDAD_CANT[EDAD_CANT < 999 & EDAD_TIPO == 1]
summary(edad)
shapiro.test(edad[0:5000])
ad.test(edad)
hist(edad, breaks = "Sturges", freq = F, plot = T)

```


```{r}
edad
range(edad)
cortes <- seq(0, 125, by=5)
edad.cut <- cut(edad, cortes, right = FALSE)
edad.freq <- table(edad.cut)

total <- rep(sum(edad.freq), 25)
edad.relfreq = edad.freq / total
edad.cumfreq <- c(0,cumsum(edad.freq))
edad.relcumfreq <- c(cumsum(edad.relfreq))

cbind(edad.freq, edad.relfreq, edad.cumfreq, edad.relcumfreq*100)
```


```{r}
plot(cortes[1:(length(cortes)-1)], (edad.relcumfreq)*100,
     main="Edad defunciones",
     xlab = "Edad en años",
     ylab = "Frecuencias relativas acumuladas")
lines(cortes[1:(length(cortes)-1)], (edad.relcumfreq)*100)
```



```{r}
boxplot(edad)
```



